language: node_js
sudo: required
before_install:
- docker login-u "charnwut02" -p"ch9a1rn02"
install: true
before_script:
- export DOCKER_HOST="charnwut02"
script:
- docker build -t charnwut02/htmltest .
- docker push charnwut02/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d --name htmltest charnwut02/htmltest:lastest
service: docker
env:
  global:
  - secure: asXIHRv7biKoSpwBNJPFq+DdYj+fJChJWVfPp6AxZJ9H/O0PmbM13XMn/Q2FJaFy0wochOUNRInTMWbMzur8rbo8ldt7qm6hvgwdPmiUTyG4tx26qL/fV4DcA0+nl8df1js5dhp01cIAiOzwUZ4iJpceDyoj71+0HWFWKSV/8G7loUM5ldlkyPwBlnK2KnvdkIQ+fQhgQGj7+nXy8eJKs+nSOA32/LfiBLEyLCbnPNg6xs2Q5LK95B3dk2Zk26fr4FHz5taFw4KnM1R1gj6ftHSNYGu86v9QYWXNZ32ycUCWO6EEeHr5LzVXBRPNm9o1kfm/EDgTgfy+EhKSvGPOlqBDDs1MOp3Dc8tqnYKnOG45qvVWO7bzt99bFXnz9+dK2e6uPXXfG5wjWho++MnRBwLpMzepln1KcKz9MuMO3V/M4cZPB+PTJSj69Dx2uDgbWe1fx29ibtX1rKRVvVxbTG8IcLoB3DQ4P6VdrOEaNqhNSdOErPDAMSqqeRAFgV+je5FXCrbG3vkQK5DGBarFgSzsbhign4d4VIWZcCsuFOhf/31oVYdfvRjl5p2kYAG/br89hzFG2o2cDZnxWNLEetxmV+F1RWvKXVvIzQJHmERji7IYLkYC6NkiIX6Re/Gw2S7oAl4jspriG9Q+fo/TbyVD6ddbFHAbKrqlSAHCn3Y=
  - secure: ES8zcHWL+l8wxeclwiOMv6yT0y600spAy91xS8ABhVL1G8/wpT9Pu1uME0/Od/Wy3VX2jXrR/Zulc8DymvNJF2VyBZZNLtuQCWKaNVY1steWTwnhEMy7aGs3L7dYqVfLprQp8i6SrlFlsJRv/pJ5ZNEcI4t9ZTWx8FQyOsIgl2/n0htdNNNUHAje6HeKj1C4zvrBVU0bgxUTbnH+LmYO/aKqtozQHPJ7yTLy4J2MjsDQIq0gMOozlefXIvvh0Gnp8CKWGqUcxU+p1EFnBQ0em9ziTU6STlZnHUS/qML6AmdOFB4QDCfPzGxQHOhEIQ73dXGiobg7JDcvgL5wWN9nPV3nP0QvJGa+6aqgqYxvprtwdh/4zU8iGBWhysfk1I8SJ+M2RP+Qg3H/BriS9iwtcyegeVJcWKPVVRMbKPus721+yCiZzKVlXocEIklckeMMQWsGJnGSoUdo9iFC/0XrQhXxpvnA0AGclYd1pYLJjtE9VyM1Uou7IIUpHUk6JzGqmdeYwz54PK+jFcBpqMKGcYGVEq0aaHtmEjNpztvHgqI4Sdhh98Q4yiGXOKmO4g8SX5L11UmzC5dbRBDIlwZICsBEy4pAcNugIFQpo78S5NZWQIQSjCLlTbkJnWS9EWXTGsujbs/VtKX+UQ4DNcjLL4lEu83ImeeWnNq0x4RwP+M=
dd:
  secure: ILWwXHAetjVO7fZeyBoQYr0ZrjDBoseRRFeYDOTLdNUR5k1qbyWiMs+l6ssWh6lcpC8mfuDgxIC3sbj4HOahkY6WfuBFNM7C5txgFXL/Ychwu9You1iYoM11v1PMWvBVj2rsrq2s7EKZjaHF+lfuPDpoenNdHTWRxMx1TQ4SuLfJwVPuslhe3/UKG5LkCV/kO9JpgynsjbJ7v/BtdRqDIkXO/s5kJX8RSdw5qwdymZ6e6uV7V0Kswon0/qdKuT3I+Jtcy2iUvIl5BIh9eMWgCHpqnNM+kIy1xCbEI47pqoonIjQLJj5gnvJ9/IXMrgLbCnPmkUON6W22VjKYXA7PdK+6pYOfCqmGV8OZ+RHpl+hXZzDnEwAS1zOFTP8buQR3ROpquc7yHcZL/tEISX7ZdFrSEH9A66RlAlBsjvfPKC3vfOVaFuL4Ovkxbl/WXCrMId1cIcTkd6AXMSeMN/VqMwud306hJAUwD5vYXA2Yc5yQntyMxpvN7tZv47E3v+2MPHWdffxGuDdFjVok3DKQrnC45gCduK+RyRkR+5uPS6Hp6Yodwa+JM65u+BIFFzPYJ2AnoXVWIyT7rmTDUEgtgYgOaoFsxUIKMQ3uJi5oIP7+LqSKj1BijoB6gvWMBJW7RgKtp2D3M+l8gW76ixFsxBt3tLEkKDZXmsxZSVHsCwE=
